---
  el:
    hosts:
      centos7:
        ansible_connection: docker
        ansible_remote_tmp: /tmp
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
        ansible_remote_tmp: /tmp
  fedora:
    hosts:
      fedora:
        ansible_connection: docker
        ansible_remote_tmp: /tmp
  local:
    hosts:
      localhost:
        ansible_connection: local